name: benchmark
channels:
  - defaults
dependencies:
  - pip=20.*
  - python=2.7.*
  - ipykernel
  - jupyter
  - pip:
      - numpy
      - pandas
#      - auto-sklearn==0.11.0
#      - tpot==0.11.6
      - scikit-learn
#      - atm==0.2.2
#      - matplotlib
#      - seaborn
#      - scipy


